### ISSUE TITLE
TomlDecodeError: Invalid date or number

### ISSUE THREAD

**Issue by swarajban** [vectara/vectara-ingest#111]
Seeing this when trying to start a crawl:
```
2024-08-15 16:34:09 2024-08-15 23:34:09,528 - root - INFO - Starting the Crawler...
2024-08-15 16:34:09 INFO:root:Starting the Crawler...
2024-08-15 16:34:09 Traceback (most recent call last):
2024-08-15 16:34:09   File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 511, in loads
2024-08-15 16:34:09     ret = decoder.load_line(line, currentlevel, multikey,
2024-08-15 16:34:09   File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 737, in load_line
2024-08-15 16:34:09     raise ValueError("Invalid date or number")
2024-08-15 16:34:09 ValueError: Invalid date or number
2024-08-15 16:34:09 
2024-08-15 16:34:09 During handling of the above exception, another exception occurred:
2024-08-15 16:34:09 
2024-08-15 16:34:09 Traceback (most recent call last):
2024-08-15 16:34:09   File "/home/vectara/ingest.py", line 164, in <module>
2024-08-15 16:34:09     main()
2024-08-15 16:34:09   File "/home/vectara/ingest.py", line 92, in main
2024-08-15 16:34:09     env_dict = toml.load(f)
2024-08-15 16:34:09   File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 156, in load
2024-08-15 16:34:09     return loads(f.read(), _dict, decoder)
2024-08-15 16:34:09   File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 514, in loads
2024-08-15 16:34:09     raise TomlDecodeError(str(err), original, pos)
2024-08-15 16:34:09 toml.decoder.TomlDecodeError: Invalid date or number (line 5 column 1 char 91)

```

Secrets
```
[general]
OPENAI_API_KEY="sk-...only needed in case you use table summarize..."

[default]
api_key=<redacted>
NOTION_API_KEY=<redacted>
```

Config
```
vectara:
  corpus_id: 2
  customer_id: 901915736
  reindex: true
  summarize_tables: false
  verbose: true
  timeout: 90

crawling:
  crawler_type: notion
```

**Comment by ofermend** [comment]
Thanks for reporting
From the error message: "2024-08-15 16:34:09 toml.decoder.TomlDecodeError: Invalid date or number (line 5 column 1 char 91)" - it appears like it's having a hard time reading your secrets.toml file on line 5 (the NOTION_API_KEY line I think, if it starts from 0). Can u pls check again if the NOTION_API_KEY itself (that is redacted here) has something that appears like a date", and maybe check if putting quotes around it helps?

**Comment by swarajban** [comment]
@ofermend thanks, putting the vectara & notion API keys fixed the TomlDecodeError, but the crawler is not finding any pages in my Notion, I'll open a separate issue.
